<?php

namespace ContainerCh2Qjg5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4516oZ1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4516oZ1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4516oZ1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'tape' => ['privates', '.errored..service_locator.4516oZ1.App\\Entity\\Tape', NULL, 'Cannot autowire service ".service_locator.4516oZ1": it references class "App\\Entity\\Tape" but no such service exists.'],
        ], [
            'managerRegistry' => '?',
            'tape' => 'App\\Entity\\Tape',
        ]);
    }
}
