<?php

namespace ContainerCh2Qjg5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStofDoctrineExtensions_Uploadable_ManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'stof_doctrine_extensions.uploadable.manager' shared service.
     *
     * @return \Stof\DoctrineExtensionsBundle\Uploadable\UploadableManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/stof/doctrine-extensions-bundle/src/Uploadable/UploadableManager.php';

        return $container->services['stof_doctrine_extensions.uploadable.manager'] = new \Stof\DoctrineExtensionsBundle\Uploadable\UploadableManager(($container->privates['stof_doctrine_extensions.listener.uploadable'] ?? $container->load('getStofDoctrineExtensions_Listener_UploadableService')), 'Stof\\DoctrineExtensionsBundle\\Uploadable\\UploadedFileInfo');
    }
}
