<?php

namespace ContainerJKM9x7d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTapeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TapeType' shared autowired service.
     *
     * @return \App\Form\TapeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TapeType.php';

        return $container->privates['App\\Form\\TapeType'] = new \App\Form\TapeType();
    }
}
