<?php

namespace ContainerTNK2lFl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTape2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fLDn9bG.App\Entity\Tape' shared service.
     *
     * @return \App\Entity\Tape
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fLDn9bG": it references class "App\\Entity\\Tape" but no such service exists.');
    }
}
