<?php

namespace ContainerTYyia7f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EiWvEfvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eiWvEfv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eiWvEfv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'artist' => ['privates', '.errored..service_locator.eiWvEfv.App\\Entity\\Artist', NULL, 'Cannot autowire service ".service_locator.eiWvEfv": it references class "App\\Entity\\Artist" but no such service exists.'],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'artist' => 'App\\Entity\\Artist',
            'managerRegistry' => '?',
        ]);
    }
}
