<?php

namespace ContainerTYyia7f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ia1UUdOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ia1UUdO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ia1UUdO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'em' => '?',
        ]);
    }
}
