<?php

namespace ContainerTYyia7f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTapeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4516oZ1.App\Entity\Tape' shared service.
     *
     * @return \App\Entity\Tape
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4516oZ1": it references class "App\\Entity\\Tape" but no such service exists.');
    }
}
