<?php

namespace ContainerAUMnhmZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DliG0z3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DliG0z3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DliG0z3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'user' => ['privates', '.errored..service_locator.DliG0z3.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.DliG0z3": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'managerRegistry' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
