<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTfmgx4s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTfmgx4s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTfmgx4s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTfmgx4s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTfmgx4s\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tfmgx4s',
    'container.build_id' => 'a63a8aa5',
    'container.build_time' => 1667155845,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTfmgx4s');
