<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTYyia7f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTYyia7f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTYyia7f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTYyia7f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTYyia7f\App_KernelDevDebugContainer([
    'container.build_hash' => 'TYyia7f',
    'container.build_id' => 'f96d134c',
    'container.build_time' => 1667109733,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTYyia7f');
